#!/bin/sh

sxhkd &
./.fehbg &
$HOME/.config/polybar/launch.sh
cd $HOME/dotfiles/scripts && python generate-background.py && feh --bg-fill wallpaper.png

bspc monitor -d I II III IV

bspc config border_width         1
bspc config normal_border_color \#2e3440
bspc config active_border_color \#8fbcbb
bspc config focused_border_color \#8fbcbb
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
