#!/bin/sh

sxhkd &
./.fehbg &
$HOME/.config/polybar/launch.sh &
cd $HOME/dotfiles/scripts && python generate-background.py &
feh --bg-fill wallpaper.png
compton &
gnome-keyring-daemon --start

bspc monitor HDMI-1 -d I II 
bspc monitor DVI-D-1 -d III IV V

bspc config border_width         1
bspc config normal_border_color \#2e3440
bspc config active_border_color \#8fbcbb
bspc config focused_border_color \#8fbcbb
bspc config window_gap          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
